{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "bd796958-c2ba-46d9-8954-ffb9ae1de224",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Match 1 was found at 0-116: [2022-01-19 11:55:04,219] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_CSV.py took 5.120 seconds\n",
      "\n",
      "Group 1 found at 1-24: 2022-01-19 11:55:04,219\n",
      "Group 2 found at 45-49: INFO\n",
      "Group 3 found at 49-116:  - Processing /opt/airflow/dags/MySQL_to_CSV.py took 5.120 seconds\n",
      "\n",
      "Group 4 found at -1--1: None\n",
      "Match 2 was found at 116-239: [2022-01-19 11:55:34,413] {processor.py:163} INFO - Started process (PID=451) to work on /opt/airflow/dags/MySQL_to_CSV.py\n",
      "\n",
      "Group 1 found at 117-140: 2022-01-19 11:55:34,413\n",
      "Group 2 found at 161-165: INFO\n",
      "Group 3 found at 165-239:  - Started process (PID=451) to work on /opt/airflow/dags/MySQL_to_CSV.py\n",
      "\n",
      "Group 4 found at -1--1: None\n",
      "Match 3 was found at 239-360: [2022-01-19 11:55:34,417] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_CSV.py for tasks to queue\n",
      "\n",
      "Group 1 found at 240-263: 2022-01-19 11:55:34,417\n",
      "Group 2 found at 284-288: INFO\n",
      "Group 3 found at 288-360:  - Processing file /opt/airflow/dags/MySQL_to_CSV.py for tasks to queue\n",
      "\n",
      "Group 4 found at -1--1: None\n",
      "Match 4 was found at 360-416: [2022-01-19 12:09:57,089] {logging_mixin.py:109} INFO - \n",
      "Group 1 found at 361-384: 2022-01-19 12:09:57,089\n",
      "Group 2 found at 409-413: INFO\n",
      "Group 3 found at 413-416:  - \n",
      "Group 4 found at -1--1: None\n",
      "Match 5 was found at 416-534: [2022-01-19 12:09:57,088] {dag.py:2914} INFO - Setting next_dagrun for second_assingnment to 2022-01-19T12:00:00+00:00\n",
      "Group 1 found at -1--1: None\n",
      "Group 2 found at -1--1: None\n",
      "Group 3 found at -1--1: None\n",
      "Group 4 found at 416-534: [2022-01-19 12:09:57,088] {dag.py:2914} INFO - Setting next_dagrun for second_assingnment to 2022-01-19T12:00:00+00:00\n",
      "Match 6 was found at 534-534: \n",
      "Group 1 found at -1--1: None\n",
      "Group 2 found at -1--1: None\n",
      "Group 3 found at -1--1: None\n",
      "Group 4 found at 534-534: \n",
      "Match 7 was found at 535-2862: [2022-01-19 12:09:57,101] {processor.py:174} ERROR - Got an exception! Propagating...\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py\", line 168, in _run_file_processor\n",
      "    callback_requests=callback_requests,\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py\", line 70, in wrapper\n",
      "    return func(*args, session=session, **kwargs)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py\", line 641, in process_file\n",
      "    dagbag.sync_to_db()\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py\", line 70, in wrapper\n",
      "    return func(*args, session=session, **kwargs)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py\", line 608, in sync_to_db\n",
      "    for attempt in run_with_db_retries(logger=self.log):\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py\", line 382, in __iter__\n",
      "    do = self.iter(retry_state=retry_state)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py\", line 349, in iter\n",
      "    return fut.result()\n",
      "  File \"/usr/local/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py\", line 622, in sync_to_db\n",
      "    DAG.bulk_write_to_db(self.dags.values(), session=session)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py\", line 67, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py\", line 2470, in bulk_write_to_db\n",
      "    DagCode.bulk_sync_to_db(filelocs, session=session)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py\", line 67, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagcode.py\", line 113, in bulk_sync_to_db\n",
      "    os.path.getmtime(correct_maybe_zipped(fileloc)), tz=timezone.utc\n",
      "  File \"/usr/local/lib/python3.7/genericpath.py\", line 55, in getmtime\n",
      "    return os.stat(filename).st_mtime\n",
      "FileNotFoundError: \n",
      "Group 1 found at 536-559: 2022-01-19 12:09:57,101\n",
      "Group 2 found at 580-585: ERROR\n",
      "Group 3 found at 585-2862:  - Got an exception! Propagating...\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py\", line 168, in _run_file_processor\n",
      "    callback_requests=callback_requests,\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py\", line 70, in wrapper\n",
      "    return func(*args, session=session, **kwargs)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py\", line 641, in process_file\n",
      "    dagbag.sync_to_db()\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py\", line 70, in wrapper\n",
      "    return func(*args, session=session, **kwargs)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py\", line 608, in sync_to_db\n",
      "    for attempt in run_with_db_retries(logger=self.log):\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py\", line 382, in __iter__\n",
      "    do = self.iter(retry_state=retry_state)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py\", line 349, in iter\n",
      "    return fut.result()\n",
      "  File \"/usr/local/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/local/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py\", line 622, in sync_to_db\n",
      "    DAG.bulk_write_to_db(self.dags.values(), session=session)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py\", line 67, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py\", line 2470, in bulk_write_to_db\n",
      "    DagCode.bulk_sync_to_db(filelocs, session=session)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py\", line 67, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagcode.py\", line 113, in bulk_sync_to_db\n",
      "    os.path.getmtime(correct_maybe_zipped(fileloc)), tz=timezone.utc\n",
      "  File \"/usr/local/lib/python3.7/genericpath.py\", line 55, in getmtime\n",
      "    return os.stat(filename).st_mtime\n",
      "FileNotFoundError: \n",
      "Group 4 found at -1--1: None\n",
      "Match 8 was found at 2862-2934: [Errno 2] No such file or directory: '/opt/airflow/dags/MySQL_to_CSV.py'\n",
      "Group 1 found at -1--1: None\n",
      "Group 2 found at -1--1: None\n",
      "Group 3 found at -1--1: None\n",
      "Group 4 found at 2862-2934: [Errno 2] No such file or directory: '/opt/airflow/dags/MySQL_to_CSV.py'\n",
      "Match 9 was found at 2934-2934: \n",
      "Group 1 found at -1--1: None\n",
      "Group 2 found at -1--1: None\n",
      "Group 3 found at -1--1: None\n",
      "Group 4 found at 2934-2934: \n",
      "Match 10 was found at 2935-3058: [2022-01-19 12:10:09,495] {processor.py:163} INFO - Started process (PID=3925) to work on /opt/airflow/dags/MySQL_to_CSV.py\n",
      "Group 1 found at 2936-2959: 2022-01-19 12:10:09,495\n",
      "Group 2 found at 2980-2984: INFO\n",
      "Group 3 found at 2984-3058:  - Started process (PID=3925) to work on /opt/airflow/dags/MySQL_to_CSV.py\n",
      "Group 4 found at -1--1: None\n",
      "Match 11 was found at 3058-3058: \n",
      "Group 1 found at -1--1: None\n",
      "Group 2 found at -1--1: None\n",
      "Group 3 found at -1--1: None\n",
      "Group 4 found at 3058-3058: \n"
     ]
    }
   ],
   "source": [
    "# coding=utf8\n",
    "# the above tag defines encoding for this document and is for Python 2.x compatibility\n",
    "\n",
    "import re\n",
    "\n",
    "regex = r\"^\\[(\\d+-\\d+-\\d+\\s\\d+:\\d+:\\d+,\\d+)\\] \\{\\S+\\} (DEBUG|INFO|WARN|FATAL|ERROR|TRACE)([^][]*)|(.*)\"\n",
    "\n",
    "test_str = (\"[2022-01-19 11:55:04,219] {processor.py:171} INFO - Processing /opt/airflow/dags/MySQL_to_CSV.py took 5.120 seconds\\n\"\n",
    "\t\"[2022-01-19 11:55:34,413] {processor.py:163} INFO - Started process (PID=451) to work on /opt/airflow/dags/MySQL_to_CSV.py\\n\"\n",
    "\t\"[2022-01-19 11:55:34,417] {processor.py:620} INFO - Processing file /opt/airflow/dags/MySQL_to_CSV.py for tasks to queue\\n\"\n",
    "\t\"[2022-01-19 12:09:57,089] {logging_mixin.py:109} INFO - [2022-01-19 12:09:57,088] {dag.py:2914} INFO - Setting next_dagrun for second_assingnment to 2022-01-19T12:00:00+00:00\\n\"\n",
    "\t\"[2022-01-19 12:09:57,101] {processor.py:174} ERROR - Got an exception! Propagating...\\n\"\n",
    "\t\"Traceback (most recent call last):\\n\"\n",
    "\t\"  File \\\"/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py\\\", line 168, in _run_file_processor\\n\"\n",
    "\t\"    callback_requests=callback_requests,\\n\"\n",
    "\t\"  File \\\"/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py\\\", line 70, in wrapper\\n\"\n",
    "\t\"    return func(*args, session=session, **kwargs)\\n\"\n",
    "\t\"  File \\\"/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py\\\", line 641, in process_file\\n\"\n",
    "\t\"    dagbag.sync_to_db()\\n\"\n",
    "\t\"  File \\\"/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py\\\", line 70, in wrapper\\n\"\n",
    "\t\"    return func(*args, session=session, **kwargs)\\n\"\n",
    "\t\"  File \\\"/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py\\\", line 608, in sync_to_db\\n\"\n",
    "\t\"    for attempt in run_with_db_retries(logger=self.log):\\n\"\n",
    "\t\"  File \\\"/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py\\\", line 382, in __iter__\\n\"\n",
    "\t\"    do = self.iter(retry_state=retry_state)\\n\"\n",
    "\t\"  File \\\"/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py\\\", line 349, in iter\\n\"\n",
    "\t\"    return fut.result()\\n\"\n",
    "\t\"  File \\\"/usr/local/lib/python3.7/concurrent/futures/_base.py\\\", line 428, in result\\n\"\n",
    "\t\"    return self.__get_result()\\n\"\n",
    "\t\"  File \\\"/usr/local/lib/python3.7/concurrent/futures/_base.py\\\", line 384, in __get_result\\n\"\n",
    "\t\"    raise self._exception\\n\"\n",
    "\t\"  File \\\"/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py\\\", line 622, in sync_to_db\\n\"\n",
    "\t\"    DAG.bulk_write_to_db(self.dags.values(), session=session)\\n\"\n",
    "\t\"  File \\\"/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py\\\", line 67, in wrapper\\n\"\n",
    "\t\"    return func(*args, **kwargs)\\n\"\n",
    "\t\"  File \\\"/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py\\\", line 2470, in bulk_write_to_db\\n\"\n",
    "\t\"    DagCode.bulk_sync_to_db(filelocs, session=session)\\n\"\n",
    "\t\"  File \\\"/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py\\\", line 67, in wrapper\\n\"\n",
    "\t\"    return func(*args, **kwargs)\\n\"\n",
    "\t\"  File \\\"/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagcode.py\\\", line 113, in bulk_sync_to_db\\n\"\n",
    "\t\"    os.path.getmtime(correct_maybe_zipped(fileloc)), tz=timezone.utc\\n\"\n",
    "\t\"  File \\\"/usr/local/lib/python3.7/genericpath.py\\\", line 55, in getmtime\\n\"\n",
    "\t\"    return os.stat(filename).st_mtime\\n\"\n",
    "\t\"FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/MySQL_to_CSV.py'\\n\"\n",
    "\t\"[2022-01-19 12:10:09,495] {processor.py:163} INFO - Started process (PID=3925) to work on /opt/airflow/dags/MySQL_to_CSV.py\")\n",
    "\n",
    "matches = re.finditer(regex, test_str, re.MULTILINE)\n",
    "\n",
    "for matchNum, match in enumerate(matches, start=1):\n",
    "    \n",
    "    print (\"Match {matchNum} was found at {start}-{end}: {match}\".format(matchNum = matchNum, start = match.start(), end = match.end(), match = match.group()))\n",
    "    \n",
    "    for groupNum in range(0, len(match.groups())):\n",
    "        groupNum = groupNum + 1\n",
    "        \n",
    "        print (\"Group {groupNum} found at {start}-{end}: {group}\".format(groupNum = groupNum, start = match.start(groupNum), end = match.end(groupNum), group = match.group(groupNum)))\n",
    "\n",
    "# Note: for Python 2.7 compatibility, use ur\"\" to prefix the regex and u\"\" to prefix the test string and substitution.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "68b9bd76-7171-499c-830c-fece7819d066",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Untitled.ipynb           airflow log regexp.ipynb\n"
     ]
    }
   ],
   "source": [
    "!ls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "21decd5f-f226-4427-8b47-e043cc46fa50",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/mdgome/workspace/study/StudyDataEngineering/StudyDataEngineering/miniporject#2/code\n"
     ]
    }
   ],
   "source": [
    "!pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3fa42d85-8ea7-40a8-9141-439c327dbde9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pipeline",
   "language": "python",
   "name": "pipeline"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
